// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

import { Metadata, asErrorResult, asTextContentResult } from 'brand.dev-mcp/tools/types';

import { Tool } from '@modelcontextprotocol/sdk/types.js';
import BrandDev from 'brand.dev';

export const metadata: Metadata = {
  resource: 'brand',
  operation: 'read',
  tags: [],
  httpMethod: 'get',
  httpPath: '/brand/transaction_identifier',
};

export const tool: Tool = {
  name: 'identify_from_transaction_brand',
  description:
    'Endpoint specially designed for platforms that want to identify transaction data by the transaction title.',
  inputSchema: {
    type: 'object',
    properties: {
      transaction_info: {
        type: 'string',
        description: 'Transaction information to identify the brand',
      },
      city: {
        type: 'string',
        description: 'Optional city name to prioritize when searching for the brand.',
      },
      country_gl: {
        type: 'string',
        description:
          'Optional country code (GL parameter) to specify the country. This affects the geographic location used for search queries.',
        enum: [
          'ad',
          'ae',
          'af',
          'ag',
          'ai',
          'al',
          'am',
          'an',
          'ao',
          'aq',
          'ar',
          'as',
          'at',
          'au',
          'aw',
          'az',
          'ba',
          'bb',
          'bd',
          'be',
          'bf',
          'bg',
          'bh',
          'bi',
          'bj',
          'bm',
          'bn',
          'bo',
          'br',
          'bs',
          'bt',
          'bv',
          'bw',
          'by',
          'bz',
          'ca',
          'cc',
          'cd',
          'cf',
          'cg',
          'ch',
          'ci',
          'ck',
          'cl',
          'cm',
          'cn',
          'co',
          'cr',
          'cu',
          'cv',
          'cx',
          'cy',
          'cz',
          'de',
          'dj',
          'dk',
          'dm',
          'do',
          'dz',
          'ec',
          'ee',
          'eg',
          'eh',
          'er',
          'es',
          'et',
          'fi',
          'fj',
          'fk',
          'fm',
          'fo',
          'fr',
          'ga',
          'gb',
          'gd',
          'ge',
          'gf',
          'gh',
          'gi',
          'gl',
          'gm',
          'gn',
          'gp',
          'gq',
          'gr',
          'gs',
          'gt',
          'gu',
          'gw',
          'gy',
          'hk',
          'hm',
          'hn',
          'hr',
          'ht',
          'hu',
          'id',
          'ie',
          'il',
          'in',
          'io',
          'iq',
          'ir',
          'is',
          'it',
          'jm',
          'jo',
          'jp',
          'ke',
          'kg',
          'kh',
          'ki',
          'km',
          'kn',
          'kp',
          'kr',
          'kw',
          'ky',
          'kz',
          'la',
          'lb',
          'lc',
          'li',
          'lk',
          'lr',
          'ls',
          'lt',
          'lu',
          'lv',
          'ly',
          'ma',
          'mc',
          'md',
          'mg',
          'mh',
          'mk',
          'ml',
          'mm',
          'mn',
          'mo',
          'mp',
          'mq',
          'mr',
          'ms',
          'mt',
          'mu',
          'mv',
          'mw',
          'mx',
          'my',
          'mz',
          'na',
          'nc',
          'ne',
          'nf',
          'ng',
          'ni',
          'nl',
          'no',
          'np',
          'nr',
          'nu',
          'nz',
          'om',
          'pa',
          'pe',
          'pf',
          'pg',
          'ph',
          'pk',
          'pl',
          'pm',
          'pn',
          'pr',
          'ps',
          'pt',
          'pw',
          'py',
          'qa',
          're',
          'ro',
          'rs',
          'ru',
          'rw',
          'sa',
          'sb',
          'sc',
          'sd',
          'se',
          'sg',
          'sh',
          'si',
          'sj',
          'sk',
          'sl',
          'sm',
          'sn',
          'so',
          'sr',
          'st',
          'sv',
          'sy',
          'sz',
          'tc',
          'td',
          'tf',
          'tg',
          'th',
          'tj',
          'tk',
          'tl',
          'tm',
          'tn',
          'to',
          'tr',
          'tt',
          'tv',
          'tw',
          'tz',
          'ua',
          'ug',
          'um',
          'us',
          'uy',
          'uz',
          'va',
          'vc',
          've',
          'vg',
          'vi',
          'vn',
          'vu',
          'wf',
          'ws',
          'ye',
          'yt',
          'za',
          'zm',
          'zw',
        ],
      },
      force_language: {
        type: 'string',
        description: 'Optional parameter to force the language of the retrieved brand data.',
        enum: [
          'albanian',
          'arabic',
          'azeri',
          'bengali',
          'bulgarian',
          'cebuano',
          'croatian',
          'czech',
          'danish',
          'dutch',
          'english',
          'estonian',
          'farsi',
          'finnish',
          'french',
          'german',
          'hausa',
          'hawaiian',
          'hindi',
          'hungarian',
          'icelandic',
          'indonesian',
          'italian',
          'kazakh',
          'kyrgyz',
          'latin',
          'latvian',
          'lithuanian',
          'macedonian',
          'mongolian',
          'nepali',
          'norwegian',
          'pashto',
          'pidgin',
          'polish',
          'portuguese',
          'romanian',
          'russian',
          'serbian',
          'slovak',
          'slovene',
          'somali',
          'spanish',
          'swahili',
          'swedish',
          'tagalog',
          'turkish',
          'ukrainian',
          'urdu',
          'uzbek',
          'vietnamese',
          'welsh',
        ],
      },
      maxSpeed: {
        type: 'boolean',
        description:
          'Optional parameter to optimize the API call for maximum speed. When set to true, the API will skip time-consuming operations for faster response at the cost of less comprehensive data.',
      },
      mcc: {
        type: 'string',
        description:
          'Optional Merchant Category Code (MCC) to help identify the business category/industry. ',
      },
      phone: {
        type: 'number',
        description: 'Optional phone number from the transaction to help verify brand match.',
      },
      timeoutMS: {
        type: 'integer',
        description:
          'Optional timeout in milliseconds for the request. If the request takes longer than this value, it will be aborted with a 408 status code. Maximum allowed value is 300000ms (5 minutes).',
      },
    },
    required: ['transaction_info'],
  },
  annotations: {
    readOnlyHint: true,
  },
};

export const handler = async (client: BrandDev, args: Record<string, unknown> | undefined) => {
  const body = args as any;
  try {
    return asTextContentResult(await client.brand.identifyFromTransaction(body));
  } catch (error) {
    if (error instanceof BrandDev.APIError) {
      return asErrorResult(error.message);
    }
    throw error;
  }
};

export default { metadata, tool, handler };
